/*
 * This source file was generated by the Gradle 'init' task
 */
package minecraft.llm;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void modInitializes() {
        // Simple test to verify the mod class can be instantiated
        LLMCommandMod mod = new LLMCommandMod();
        assertNotNull(mod, "LLMCommandMod should be instantiated");
    }
}
